spring:
  main:
    web-application-type: none
    banner-mode: off
  ai:
    mcp:
      server:
        name: my-weather-server
        version: 0.0.1

# 注意：您必须禁用横幅和控制台日志记录，以允许 STDIO 传输!!工作  banner-mode: off
logging:
  level:
    root: ERROR
    org.springframework.ai: ERROR
    com.xs.ai: ERROR
  file:
    name: logs/mcp-server.log
  pattern:
    console: